services:
  docker-remote-backup:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro     # Use host machine timezone
      - ./logs:/logs                         # Directory for logs
      - ./hooks:/hooks:ro                    # Directory of hook scripts
      - ${SOURCE_CONTEXT_DIRECTORY}:/data:ro # Directory to sync
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env

